name: Build PDF

on:
  push:
    paths: [rumble-api.yml]

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Generate HTML docs
        run: npx openapi-generator-cli generate -i rumble-api.yml -g html -o pdfgen/html -c pdfgen/config.yaml
      - name: HTML to PDF
        run: node pdfgen/makepdf.js
      - name: Commit files
        run: |
          git config --local user.name "GitHub Build PDF action"
          git add rumble-api.pdf'
          git commit -m "Update PDF"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
